name: tailor_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animations: ^2.0.11
  bloc: ^9.0.0
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  
  flutter_bloc: ^9.1.1
  get_storage: ^2.1.1
  google_fonts: ^6.3.0
  http: ^1.5.0
  intl: ^0.20.2
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/splash-screen.png
    - assets/images/splash_lets.png
    - assets/images/google_logo.png
    - assets/icons/

flutter_gen:
  output: lib/utils/