name: tailor_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  google_fonts: ^6.3.0
  http: ^1.5.0
  intl: ^0.20.2
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/utils/